title: BASTA Systems — Software Engineering Services
tagline: High-performance, low-latency software development
description: High-performance, low-latency software development
show_github_link: false
remote_theme: m-basta-systems/hacker-pages-theme@master
plugins:
- jekyll-remote-theme
