title: BASTA Systems
tagline: Software engineering services
description: Software engineering services
show_github_link: false
remote_theme: m-basta-systems/hacker-pages-theme@master
plugins:
- jekyll-remote-theme
